language: python
compiler: gcc
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export MPLBACKEND="TkAgg"
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a

  # Install the deps pip can struggle with
  - conda create -qy -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - pip install pytest-cov codecov
  - pip install extension-helpers
  - pip install jinja2
  - pip install astropy==4.3.1
  - python setup.py install

script:
  - py.test --cov=. --cov-report xml tests/

after_success:
  - codecov
